.TH "kitten-hyperlinked-grep" "1" "Jun 22, 2024" "0.35.2" "kitten Manual"
.SH Name
kitten-hyperlinked-grep \- Add hyperlinks to the output of ripgrep
.SH Usage
.SY "kitten hyperlinked-grep arguments for the rg command"
.YS
.SH Description
The hyperlinked_grep kitten is a thin wrapper around the rg command. It automatically adds hyperlinks to the output of rg allowing the user to click on search results to have them open directly in their editor. For details on its usage, see /kittens/hyperlinked_grep.
.SH Options
.TP
.BI "--help, -h" 
Show help for this command
