.TH "kitten-update-self" "1" "Jun 22, 2024" "0.35.2" "kitten Manual"
.SH Name
kitten-update-self \- Update this kitten binary
.SH Usage
.SY "kitten update-self [options]"
.YS
.SH Description
Update this kitten binary in place to the latest available version.
.SH Options
.TP
.BI "--fetch-version" " [=latest]"
The version to fetch. The special words latest and nightly fetch the latest stable and nightly release respectively. Other values can be, for example: 0.35.2.
.TP
.BI "--help, -h" 
Show help for this command
